### ISSUE TITLE
launch + join could be replaced by withContext

### ISSUE THREAD

**Issue by LouisCAD** [GeoffreyMetais/dlmanager-android#1]
Code below:
https://github.com/GeoffreyMetais/dlmanager-android/blob/62ceee1d57623c3de13f11fcad71933d1e8bd11c/app/src/main/java/org/gmetais/downloadmanager/ui/adapters/DiffUtilAdapter.kt#L24-L27
could become:
```kotlin
withContext(UI) {
    mDataset = dataSet 
    result.dispatchUpdatesTo(this@DiffUtilAdapter)
}
```
This should be more efficient as it avoids creating a new coroutine, and also, the parent job is used.

**Comment by GeoffreyMetais** [comment]
Not sure it avoids a coroutine creation as it's dispatched anyway.
But definitely better, thank you!

**Comment by LouisCAD** [comment]
@GeoffreyMetais There could be a benchmark time wise, and memory wise to see the real difference. I bet on `withContext` to win ;)

Also, the source code of `withContext` as of version 0.22.3 suggests there's a fast path if there' no context switch: https://github.com/Kotlin/kotlinx.coroutines/blob/562c1bb69a3c86e4123e710e7ad714d70958139f/core/kotlinx-coroutines-core/src/main/kotlin/kotlinx/coroutines/experimental/Builders.kt#L105

**Comment by GeoffreyMetais** [comment]
Good to know :)
